### PR TITLE
Closes #199

### LINKED ISSUE #199: 500 error on trying to notify subscribers
I thought we fixed this to handle it more gracefully. We need to use urls for lessons that are a fixed length, so short urls, or shortcodes or a url shortener would all work here.

```
2016-01-24T15:47:09.663127+00:00 heroku[router]: at=info method=POST path="/notify_subscribers/297" host=www.railsschool.org request_id=56f10ed1-b07c-4b85-b80f-39595304facf fwd="75.75.14.175,173.245.56.123" dyno=web.1 connect=1ms service=555ms status=500 bytes=906
2016-01-24T15:47:09.534580+00:00 app[web.1]: Completed 500 Internal Server Error in 548ms (ActiveRecord: 14.1ms)
2016-01-24T15:47:09.535496+00:00 app[web.1]: 
2016-01-24T15:47:09.535499+00:00 app[web.1]: ActiveRecord::StatementInvalid (PG::StringDataRightTruncation: ERROR:  value too long for type character varying(140)
2016-01-24T15:47:09.535500+00:00 app[web.1]: : UPDATE "lessons" SET "tweet_message" = $1, "notification_sent_at" = $2, "updated_at" = $3 WHERE "lessons"."id" = $4):
2016-01-24T15:47:09.535502+00:00 app[web.1]: 
2016-01-24T15:47:09.535503+00:00 app[web.1]: 
2016-01-24T15:47:09.535501+00:00 app[web.1]:   app/controllers/users_controller.rb:50:in `notify_subscribers'
```

### PR DESCRIPTION
**Pull request by levans248**
Removed 140 character limit from tweet_message column in the lessons tables

### CODE REVIEW

**Comment by cdale77** [comment]
@levans248 thanks!

**Comment by gkop** [comment]
@levans248 did you migrate the db after merging this? /cc @btaitelb wrt #205

**Comment by levans248** [comment]
No, I did not do anything with this after pushing up my PR.

**Comment by btaitelb** [comment]
okay, running `db:migrate` now then :)

**Comment by btaitelb** [comment]
`heroku run rake db:migrate` has some pretty output.

**Pull request merged**
