### PR TITLE
adds favicon with rel = icon

### LINKED ISSUE #120: Favicon not coming up in production
On chrome on my laptop. I think maybe we need another link with rel="icon"  ?

### PR DESCRIPTION
**Pull request by nbhartiya**
Fixes #120

### CODE REVIEW

**Comment by gkop** [comment]
@nbhartiya why don't you go ahead and push this branch to production and check that it works?

**Comment by nbhartiya** [comment]
@gkop works

**Comment by nbhartiya** [comment]
does it work for you, though? I wonder if it's because I messed with it in the inspector?

**Comment by gkop** [comment]
It doesn't work for me in the latest FF or Chrome :(

**Comment by nbhartiya** [comment]
ok pushing to prod worked! merging..

**Pull request merged**
